recipe: default.v1
assistant_id: 20230327-174028-emerald-drip
language: zh

# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
pipeline:
#  - name: JiebaTokenizer
#  - name: LanguageModelFeaturizer
#    model_name: "bert"
#    model_weights: "bert-base-chinese"
#  - name: DIETClassifier
#    epochs: 100
  - name: SpacyNLP
    model: xx_ent_wiki_sm
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100


# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.05  # Fallback action is executed when bot's action confidence falls below this threshold
    core_fallback_action_name: "action_fallback"
    enable_fallback_prediction: True
